#!/usr/bin/env bash
# check-drift.sh — detect configuration drift between the frontend environment
#                  and the deployment manifest.
#
# What "drift" means here:
#   The frontend/.env file holds the contract IDs and network the UI connects
#   to.  After a fresh deployment, deploy.sh writes these values automatically.
#   Over time — especially during rapid development — the .env can fall behind
#   the latest deployed contracts, either because:
#     • a new deployment was made but .env was not updated, or
#     • .env was edited manually to point at a different contract, or
#     • the wrong network template was loaded.
#
#   This script compares frontend/.env against a deployment manifest
#   (deploy-manifest.json, written by deploy.sh) and reports any mismatches.
#   It can also run in --check-only mode for CI use.
#
# Usage:
#   bash scripts/check-drift.sh [--check-only]
#
#   --check-only   Exit 1 on any drift. Suitable for CI validation.
#                  Without this flag the script always exits 0 and prints a
#                  human-readable report (suitable for local dev warnings).
#
# Exit codes:
#   0 — no drift detected, or drift detected but --check-only was not passed
#   1 — drift detected and --check-only was passed, or fatal setup error

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/frontend/.env"
MANIFEST_FILE="$REPO_ROOT/deploy-manifest.json"

CHECK_ONLY=false
if [[ "${1:-}" == "--check-only" ]]; then
  CHECK_ONLY=true
fi

# ── Helpers ───────────────────────────────────────────────────────────────────

DRIFT_FOUND=false

ok()    { printf "  [ok]    %s\n" "$1"; }
drift() { printf "  [DRIFT] %s\n" "$1" >&2; DRIFT_FOUND=true; }
info()  { printf "  [info]  %s\n" "$1"; }
warn()  { printf "  [warn]  %s\n" "$1"; }

# ── Pre-flight checks ─────────────────────────────────────────────────────────

echo "==> Checking for configuration drift..."
echo ""

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: frontend/.env not found." >&2
  echo "       Run 'bash scripts/load-env.sh <network>' or 'bash scripts/deploy.sh' first." >&2
  exit 1
fi

if [[ ! -f "$MANIFEST_FILE" ]]; then
  warn "No deploy manifest found at deploy-manifest.json."
  warn "Drift check requires a manifest generated by deploy.sh."
  warn "Run 'bash scripts/deploy.sh <identity>' to create one."
  warn "Skipping drift check — no baseline to compare against."
  echo ""
  echo "No drift check performed (missing manifest)."
  exit 0
fi

# ── Load values ───────────────────────────────────────────────────────────────

# Source .env — only pull the VITE_* keys we care about, don't execute arbitrary code.
# shellcheck source=/dev/null
source "$ENV_FILE"

# The set of contracts checked below (rwa_token, kyc_registry, compliance_engine,
# invoice_token, property_token, carbon_credit_token) must stay in sync with
# REQUIRED_ARTIFACTS in scripts/verify-artifacts.sh. If a contract crate is
# renamed there, update the VITE_* keys and manifest keys here to match —
# otherwise the drift check silently stops covering the renamed contract.
ENV_NETWORK="${VITE_STELLAR_NETWORK:-}"
ENV_KYC="${VITE_KYC_REGISTRY_ID:-}"
ENV_CE="${VITE_COMPLIANCE_ENGINE_ID:-}"
ENV_INV="${VITE_INVOICE_TOKEN_ID:-}"
ENV_PROP="${VITE_PROPERTY_TOKEN_ID:-}"
ENV_CARBON="${VITE_CARBON_TOKEN_ID:-}"
ENV_RWA="${VITE_RWA_TOKEN_ID:-}"

# Parse manifest with sed/grep so we don't require jq.
get_manifest_value() {
  local key="$1"
  grep "\"${key}\"" "$MANIFEST_FILE" \
    | head -1 \
    | sed 's/.*"[^"]*"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/'
}

MAN_NETWORK=$(get_manifest_value "network_name")
MAN_KYC=$(get_manifest_value "kyc_registry_id")
MAN_CE=$(get_manifest_value "compliance_engine_id")
MAN_INV=$(get_manifest_value "invoice_token_id")
MAN_PROP=$(get_manifest_value "property_token_id")
MAN_CARBON=$(get_manifest_value "carbon_token_id")
MAN_DEPLOYED_AT=$(get_manifest_value "deployed_at")

echo "  Manifest deployed at : ${MAN_DEPLOYED_AT:-unknown}"
echo "  Manifest network     : ${MAN_NETWORK:-unknown}"
echo "  Active .env network  : ${ENV_NETWORK:-unset}"
echo ""

# ── Network match ─────────────────────────────────────────────────────────────

echo "==> Network"
if [[ "$ENV_NETWORK" == "$MAN_NETWORK" ]]; then
  ok "VITE_STELLAR_NETWORK matches manifest ($ENV_NETWORK)"
else
  drift "VITE_STELLAR_NETWORK mismatch: .env='${ENV_NETWORK:-unset}', manifest='${MAN_NETWORK:-unknown}'"
  drift "  The frontend is pointing at a different network than the deployed contracts."
  drift "  Fix: run 'bash scripts/load-env.sh ${MAN_NETWORK}' then redeploy, or update .env manually."
fi

# ── Contract ID comparison ────────────────────────────────────────────────────

echo ""
echo "==> Contract IDs"

compare() {
  local label="$1" env_val="$2" man_val="$3"
  if [[ -z "$man_val" ]]; then
    # Not in manifest — skip silently (optional contract)
    return
  fi
  if [[ "$env_val" == "$man_val" ]]; then
    ok "$label matches"
  elif [[ -z "$env_val" ]]; then
    drift "$label is empty in frontend/.env but manifest has: $man_val"
    drift "  Fix: add ${label/VITE_/VITE_}=$man_val to frontend/.env"
  else
    drift "$label mismatch:"
    drift "  .env      = $env_val"
    drift "  manifest  = $man_val"
    drift "  Fix: update the value in frontend/.env to match the manifest, or redeploy."
  fi
}

compare "VITE_KYC_REGISTRY_ID"      "$ENV_KYC"    "$MAN_KYC"
compare "VITE_COMPLIANCE_ENGINE_ID" "$ENV_CE"     "$MAN_CE"
compare "VITE_INVOICE_TOKEN_ID"     "$ENV_INV"    "$MAN_INV"
compare "VITE_PROPERTY_TOKEN_ID"    "$ENV_PROP"   "$MAN_PROP"
compare "VITE_CARBON_TOKEN_ID"      "$ENV_CARBON" "$MAN_CARBON"

# ── Empty value warnings ──────────────────────────────────────────────────────

echo ""
echo "==> Empty value check"
EMPTY_COUNT=0
for pair in \
  "VITE_KYC_REGISTRY_ID=$ENV_KYC" \
  "VITE_COMPLIANCE_ENGINE_ID=$ENV_CE" \
  "VITE_INVOICE_TOKEN_ID=$ENV_INV" \
  "VITE_PROPERTY_TOKEN_ID=$ENV_PROP" \
  "VITE_CARBON_TOKEN_ID=$ENV_CARBON"
do
  key="${pair%%=*}"
  val="${pair#*=}"
  if [[ -z "$val" ]]; then
    warn "$key is empty in frontend/.env — the UI will not connect to this contract"
    EMPTY_COUNT=$(( EMPTY_COUNT + 1 ))
  fi
done

if [[ "$EMPTY_COUNT" -eq 0 ]]; then
  ok "All required contract IDs are set"
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "────────────────────────────────────────────────────────────────────────────"

if $DRIFT_FOUND; then
  echo ""
  echo "Configuration drift detected. See [DRIFT] lines above for details."
  echo ""
  echo "How to resolve:"
  echo "  1. Re-run the deployment:  bash scripts/deploy.sh <identity>"
  echo "     This overwrites frontend/.env with the latest contract IDs."
  echo "  2. Or load the correct template: bash scripts/load-env.sh <network>"
  echo "     Then fill in the contract IDs from your deployment records."
  echo ""
  if $CHECK_ONLY; then
    exit 1
  fi
else
  echo ""
  echo "No drift detected. frontend/.env is consistent with deploy-manifest.json."
fi

exit 0
